// Trips routers
//Criar viagem
POST http://localhost:3000/api/trips
Content-Type: application/json

{
  "destination": "Paraiba",
  "starts_at":"2024-07-12T03:00:00.000Z",
  "ends_at":"2024-07-13T03:00:00.000Z",
  "emails_to_invite": ["diego@rocketseat.com.br", "john@acme.com"],
  "owner_email": "silva@gmail.com"
}

###
//Buscar viagem especifica
GET http://localhost:3000/api/trips/66a261b7913ab8ab4a43e116
###
//Buscar todas as viagens como chefe
GET http://localhost:3000/api/trips?email=isley@mail.com
###
//Buscar todas as viagens como participante
GET http://localhost:3000/api/trips/participants?email=silva@gmail.com
###
//Deletar participante da viagem
DELETE http://localhost:3000/api/trips/66a261b7913ab8ab4a43e116/participants/silva@gmail.com
###
//Deletar viagem
DELETE http://localhost:3000/api/trips/66967c6c209328169ecbce6b
###
//Activies
//criar atividades
POST http://localhost:3000/api/activities
Content-Type: application/json

{
  "tripId": "669832415c202a3cc20dd518",
  "date":"2024-07-12T03:00:00.000Z"
}

###
//buscar de atividade por id
GET http://localhost:3000/api/activities/669832585c202a3cc20dd51a

###
//buscar de atividades por viagem
GET http://localhost:3000/api/activities?id=669832585c202a3cc20dd51a
###
//Deletar atividades com tudo dentro
DELETE http://localhost:3000/api/activities/6696e27950402b5d6dab5203
###

//Activity
//criar um item de atividade
POST http://localhost:3000/api/activities/669832585c202a3cc20dd51a/activity
Content-Type: application/json

{
  "title": "Titulo",
  "occurs_at": "2024-07-12T03:00:00.000Z",
  "description": "Hoje vai ser demais"
}

###
//ver todos os itens de uma atividade
GET http://localhost:3000/api/activities/669832585c202a3cc20dd51a/activity
###
//Retorna um item de atividade especifico
GET http://localhost:3000/api/activities/669832585c202a3cc20dd51a/activity/669832c05c202a3cc20dd51e
###
//Deletar uma unica atividade de atividades
DELETE http://localhost:3000/api/activities/669832585c202a3cc20dd51a/activity/669832c05c202a3cc20dd51e
###

//User
//Criar usuario
//Registrar usuario no sistema
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "user": "Isley",
  "email": "Isley@mail.com",
  "password": "isley123"
}
###
//Logar no sistema
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "Isley@mail.com",
  "password": "isley123"
}

###
//ver todos os usuarios
GET http://localhost:3000/api/user
###



DELETE http://localhost:3000/api/cartas/cartas?id_carta=5&id_colecao=PokeGo
###
